apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-first-dep
  labels:
    app: kubdeployment
    dep: kubfirstdep
spec:
  selector:
    matchLabels:
      app: kubfirstpod
  replicas: 3
  template:
    metadata:
      name: kub-first-pod
      labels:
        app: kubfirstpod
        podlabel: kubfirstpod
    spec:
      containers:
        - name: kub-first-app
          image: joydipdocker/kub-first-app:v1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            # requests:
            #   memory: "128Mi"
            #   cpu: "500m"
