apiVersion: v1
kind: Service
metadata:
  name: kub-first-service
  labels:
    app: kubservice
spec:
  selector:
    app: kubfirstpod
    podlabel: kubfirstpod
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
