apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-pod
  template:
    metadata:
      labels:
        app: story-pod
    spec:
      containers:
        - name: story-container
          image: joydipdocker/story-image:v3
          # envFrom:
          #   - ./env/backend.env
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  key: folder
                  name: app-key-value-pairs
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: portno
                  name: app-key-value-pairs
          volumeMounts:
            - name: story-volume
              mountPath: /app/story
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pv-claim
