apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  selector:
    matchLabels:
      app: story-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: story-pod
    spec:
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: storypvc
      containers:
        - name: story-container
          image: joydipdocker/story-app:v2
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
