apiVersion: v1
kind: PersistentVolume
metadata:
  name: storypv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # only one worker node can use it (>=1 pods)
    # - ReadWriteMany # many worker node can use it (>=1 pods)
    # - ReadOnlyMany # many worker node can use it (>=1 pods) - can read
    # - ReadWriteOncePod # only one pod can use it
  # persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data
    type: DirectoryOrCreate
