apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storypvc
spec:
  volumeName: storypv
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
